remote-host: ${REMOTE_HOST:mopkovka.sytes.net}

spring:
  config:
    import: vault://
  cloud:
    vault:
      uri: http://${remote-host}:8200
      token: root
  kafka:
    bootstrap-servers: ${remote-host}:9093

eureka:
  client:
    service-url:
      defaultZone: http://${remote-host}:8761/eureka/

app:
  base-url: http://localhost:8081
  frontend-url: http://localhost:3000
  cookie-secure: false
