spring:
  cloud:
    vault:
      uri: http://localhost:8200
      token: root
  kafka:
    bootstrap-servers: localhost:9093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  base-url: http://localhost:8082
  frontend-url: http://localhost:3000
