spring:
  cloud:
    vault:
      uri: http://mopkovka.sytes.net:8200
      token: root
  kafka:
    bootstrap-servers: mopkovka.sytes.net:9093

eureka:
  client:
    service-url:
      defaultZone: http://mopkovka.sytes.net:8761/eureka/

app:
  base-url: http://mopkovka.sytes.net:8082
  frontend-url: http://mopkovka.sytes.net:3000
