[versions]
spring-boot = "3.4.2"
dependency-management = "1.1.7"
lombok = "1.18.42"
spring-cloud = "2024.0.1"
jjwt = "0.12.6"
jooq-plugin = "9.0"
jooq = "3.19.18"
postgresql = "42.7.3"
flyway = "10.8.1"

[libraries]
# JWT
jjwt-api     = { module = "io.jsonwebtoken:jjwt-api",     version.ref = "jjwt" }
jjwt-impl    = { module = "io.jsonwebtoken:jjwt-impl",    version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }

# Spring Boot starters
spring-boot-starter-web          = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-webflux      = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-boot-starter-actuator     = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-jooq         = { module = "org.springframework.boot:spring-boot-starter-jooq" }
spring-boot-starter-oauth2-client = { module = "org.springframework.boot:spring-boot-starter-oauth2-client" }
spring-kafka                     = { module = "org.springframework.kafka:spring-kafka" }

# Spring Cloud
spring-cloud-gateway         = { module = "org.springframework.cloud:spring-cloud-starter-gateway" }
spring-cloud-eureka-server   = { module = "org.springframework.cloud:spring-cloud-starter-netflix-eureka-server" }
spring-cloud-eureka-client   = { module = "org.springframework.cloud:spring-cloud-starter-netflix-eureka-client" }
spring-cloud-vault-config    = { module = "org.springframework.cloud:spring-cloud-starter-vault-config" }

# Database
postgresql    = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
flyway-core   = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }

# Lombok
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

[plugins]
spring-boot         = { id = "org.springframework.boot",        version.ref = "spring-boot" }
dependency-management = { id = "io.spring.dependency-management", version.ref = "dependency-management" }
jooq                = { id = "nu.studer.jooq",                   version.ref = "jooq-plugin" }
