remote-host: ${REMOTE_HOST:mopkovka.sytes.net}

spring:
  config:
    import: vault://
  cloud:
    vault:
      uri: http://${remote-host}:8200
      token: dev-vault-token

eureka:
  client:
    service-url:
      defaultZone: http://${remote-host}:8761/eureka/
